include:
  - project: flywheel-io/tools/etc/qa-ci
    ref: 6f3f7fd65e1a4a89d2028b2748280321928a346a
    file: ci/gear.yml

variables:
  PYTEST_COV_FAIL_UNDER: 80
  DEBUG: 9  # Set debug mode to print out executed command on qa-ci
