repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: 733a34273433aedacf8aa5c56bc08e61e11d4893
    hooks:
      - id: eolfix
      - id: jsonlint
      - id: markdownlint
      - id: poetry_export
      - id: yamllint

  - repo: https://gitlab.com/flywheel-io/scientific-solutions/etc/sse-qa-ci
    rev: bf2eac494c0bb46f1f769fc5c1771dfb3d644f80
    hooks:
      - id: validate-manifest
