repos:
  - repo: https://gitlab.com/flywheel-io/tools/etc/qa-ci
    rev: main
    hooks:
      - id: eolfix
      - id: gearcheck
      - id: hadolint
      - id: jsonlint
      - id: markdownlint
      - id: poetry_export
      - id: ruff
        args: []
      - id: ruff_format
      - id: ruff_tests
      - id: yamllint
