# This script is designed to be run with file-curator as a Gear Rule on Flywheel.
# Its purpose is to merge the two CSV files generated by the form-and-annotation-exporter gear.
#
# Gear Rule configuration:
#   - Target container: analysis output
#   - File name matches regex: ".*form-responses.*"
#   - Triggering input assigned to 'file-input'
#   - Curator script assigned to 'curator' as fixed input
#   - Requirements file assigned to 'additional-input-one' as fixed input
#   - Read-write permissions
#
# Workflow:
#   1. The form-and-annotations-exporter gear runs and produces two files:
#        - A form-responses file
#        - An annotations file
#
#   2. The gear rule is triggered when the form-responses file appears in the new analysis container.
#
#   3. The file-curator gear is then executed. It uses the curator script to search for both the
#      annotations file and the form-responses file within the analysis container and combines them into a new CSV.
#
#   4. Finally, a new analysis container is created to house the combined output file.

from typing import Any, Dict

from flywheel_gear_toolkit import GearToolkitContext
from flywheel_gear_toolkit.utils.curator import FileCurator


class Curator(FileCurator):
    def __init__(self, **kwargs):
        # Note that any additional packages required by the curator script should be added to the extra_packages list
        super().__init__(
            context=GearToolkitContext(), extra_packages=["polars"], **kwargs
        )

    def curate_file(self, file_: Dict[str, Any]):
        import polars as pl
        # This merge could clearly be done with pandas, just wanted to provide an example
        # where we need to install a dependency.

        # Get the parent container id from the file object
        parent_container_id = file_.get("hierarchy").get("id")

        # Use flywheel_gear_toolkit to get the actual parent container object from the id
        parent_container = self.client.get(parent_container_id)

        # Get the form_responses path from the input file object
        form_responses_path = file_.get("location").get("path")

        # Iterate through the files in the parent container to find the name of the annotations file
        annotations_filename = None
        for child_file in parent_container.files:
            if "annotations" in child_file.name:
                annotations_filename = child_file.name
                break

        # End the script if there is no annotations file to be found
        if annotations_filename is None:
            print("No annotations file found in the parent container.")
            return

        # Build a path where we want to download the annotations file
        annotations_path = self.context.work_dir / annotations_filename

        # Use the SDK to download the annotations file into the previously defined path
        # Note that self.client is set by the base class from the context
        self.client.download_output_from_container_analysis(
            parent_container.get("parent").get("id"),
            parent_container_id,
            annotations_filename,
            dest_file=annotations_path,
        )

        # Get the output path for the merged file using the flywheel_gear_toolkit
        output_path = self.context.output_dir / "merged_output_with_annotations.csv"

        # Read the CSV files using polars
        form_responses_wide_df = pl.read_csv(form_responses_path)
        annotations_wide_df = pl.read_csv(annotations_path)

        # Determine the common columns between the two dataframes excluding unwanted columns
        unwanted = {
            "Created",
            "Modified",
            "Revision",
            "Acquisition Label",
            "acquisition.id",
            "File Name",
            "file.id",
        }
        common_columns = [
            col
            for col in annotations_wide_df.columns
            if col in form_responses_wide_df.columns and col not in unwanted
        ]

        # Merge the two dataframes on the common columns using an outer join
        merged_df = annotations_wide_df.join(
            form_responses_wide_df, on=common_columns, how="outer"
        )

        # Write the merged dataframe to CSV
        merged_df.write_csv(output_path)
