[recipients]
host = "upmc-edu.mail.protection.outlook.com"
from = "no-reply@upmc.edu"
to = ["foranw@umpc.edu", "hudlowe@upmc.edu", "hudlowe@pitt.edu", "flywheelgearlist@list.pitt.edu"]

[station_map]
MRC67078 = "PRISMA1"
AWP167046 = "PRISMA2"
MRC35073 = "PRISMA3"

[z_thresholds]
PRISMA1 = 9931.513661
PRISMA2 = 4505.258657
PRISMA3 = 11652.571269

