[recipients]
host = "upmc-edu.mail.protection.outlook.com"
from = "hudlowe@upmc.edu"
to = ["foranw@umpc.edu", "hudlowe@upmc.edu", "hudlowe@pitt.edu", "flywheelgearlist@list.pitt.edu"]



# see 'nslookup -type=mx pitt.edu'
